# Generated by Django 2.1.5 on 2020-07-02 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userapi',
            options={'verbose_name': 'Userapi'},
        ),
    ]
